<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    
    <AssemblyName>DOHCLOUDFLARE</AssemblyName>
    <Authors>XoXoТач</Authors>
	<AssemblyTitle>Приложение для включения\отключения DOH Cloudflare.</AssemblyTitle>
    <Product>DOH Cloudflare</Product>
    <Version>1.0.0</Version>
    <Description>DNS-over-HTTPS switcher for Windows 11</Description>
    <Copyright>Copyright © 2025 XoXoТач</Copyright>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>cloudflare.ico</ApplicationIcon>
    <UseWindowsForms>true</UseWindowsForms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <DebugType>None</DebugType>
    <SelfContained>true</SelfContained>
    <StartupObject>Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="6.0.0" />
  </ItemGroup>

</Project>